# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-03 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialId', models.CharField(default='Not Received', max_length=100)),
                ('sensor1', models.FloatField(default=0)),
                ('sensor2', models.FloatField(default=0)),
                ('sensor3', models.FloatField(default=0)),
                ('sensor4', models.FloatField(default=0)),
                ('sensor5', models.FloatField(default=0)),
                ('sensor6', models.FloatField(default=0)),
                ('sensor7', models.FloatField(default=0)),
                ('sensor8', models.FloatField(default=0)),
                ('sensor9', models.FloatField(default=0)),
                ('time', models.CharField(default='Not Received', max_length=100)),
            ],
        ),
    ]
