# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-03 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensors',
            new_name='Course',
        ),
    ]
