# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-08 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0007_auto_20181008_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
