# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-08 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0009_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, null='True')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.topic')),
            ],
        ),
    ]
