# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-08 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0010_subtopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, null='True')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('no_of_questions', models.IntegerField()),
                ('attempts_allowed', models.IntegerField()),
                ('pass_percentage', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.Course')),
            ],
        ),
    ]
