# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-08 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0011_exam_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
