# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-23 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0013_question_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null='True')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.question_bank')),
            ],
        ),
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_no', models.IntegerField()),
                ('option_value', models.TextField(blank=True, null='True')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.question_bank')),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.IntegerField()),
                ('registered', models.IntegerField()),
                ('view_answers', models.IntegerField()),
                ('answered', models.IntegerField()),
                ('registered_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null='True')),
                ('score', models.FloatField()),
                ('verify', models.IntegerField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.question_bank')),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.registration')),
            ],
        ),
        migrations.RenameModel(
            old_name='exam_details',
            new_name='exam_detail',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null='True'),
        ),
        migrations.AlterField(
            model_name='exam_detail',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.course'),
        ),
        migrations.AddField(
            model_name='registration',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.exam_detail'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.user'),
        ),
    ]
