# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-24 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0024_auto_20181024_0809'),
        ('online_exam', '0024_auto_20181024_0805'),
    ]

    operations = [
    ]
