# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-24 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0025_merge_20181024_1358'),
        ('online_exam', '0025_auto_20181024_1713'),
    ]

    operations = [
    ]
