# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-07 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_exam', '0030_auto_20181207_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTheColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null='True')),
                ('answer', models.TextField(blank=True, null='True')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.question_bank')),
            ],
        ),
        migrations.AlterField(
            model_name='exam_detail',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.course'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_exam.user'),
        ),
    ]
